package golocation

type Language struct {
	ID        int	 `json:"id"`
	Name      string `json:"name"`
	ShortName string `json:"shortName"`
}

var languages = []Language{
	{1, "English", "EN"},
	{2, "Mandarin", "CN"},
	{3, "Spanish", "ES"},
	{4, "Hindi", "HI"},
	{5, "Arabic", "AR"},
	{6, "Bengali", "BN"},
	{7, "Russian", "RU"},
	{8, "Portuguese", "PT"},
	{9, "Japanese", "JA"},
	{10, "Punjabi", "PA"},
	{11, "German", "DE"},
	{12, "Javanese", "JV"},
	{13, "Wu (Shanghainese)", "WU"},
	{14, "Malay", "MS"},
	{15, "Telugu", "TE"},
	{16, "Vietnamese", "VI"},
	{17, "Korean", "KO"},
	{18, "French", "FR"},
	{19, "Marathi", "MR"},
	{20, "Tamil", "TA"},
	{21, "Urdu", "UR"},
	{22, "Turkish", "TR"},
	{23, "Italian", "IT"},
	{24, "Yoruba", "YO"},
	{25, "Bhojpuri", "BH"},
	{26, "Thai", "TH"},
	{27, "Gujarati", "GU"},
	{28, "Kannada", "KN"},
	{29, "Amharic", "AM"},
	{30, "Dutch", "NL"},
	{31, "Nepali", "NE"},
	{32, "Sindhi", "SD"},
	{33, "Romanian", "RO"},
	{34, "Oromo", "OM"},
	{35, "Serbian", "SR"},
	{36, "Zulu", "ZU"},
	{37, "Somali", "SO"},
	{38, "Chhattisgarhi", "CT"},
	{39, "Khmer", "KM"},
	{40, "Assamese", "AS"},
	{41, "Madurese", "MD"},
	{42, "Sinhala", "SI"},
	{43, "Marwari", "MW"},
	{44, "Haryanvi", "HA"},
	{45, "Hungarian", "HU"},
	{46, "Chewa", "NY"},
	{47, "Kinyarwanda", "RW"},
	{48, "Greek", "EL"},
	{49, "Igbo", "IG"},
	{50, "Tagalog", "TL"},
	{51, "Saraiki", "SK"},
	{52, "Nigerian Pidgin", "NG"},
	{53, "Bavarian", "BAR"},
	{54, "Swedish", "SV"},
	{55, "Xhosa", "XH"},
	{56, "Tajik", "TG"},
	{57, "Burmese", "MY"},
	{58, "Ukrainian", "UK"},
	{59, "Northern Uzbek", "KAR"},
	{60, "Uyghur", "UG"},
	{61, "Rundi", "RN"},
	{62, "Kazakh", "KK"},
	{63, "Kongo", "KG"},
	{64, "Tatar", "TT"},
	{65, "Haitian Creole", "HT"},
	{66, "Luxembourgish", "LB"},
	{67, "Armenian", "HY"},
	{68, "Limburgish", "LI"},
	{69, "Zazaki", "DIQ"},
	{70, "Norwegian Bokmål", "NO"},
	{71, "Hmong", "HMN"},
	{72, "Sicilian", "SCN"},
	{73, "Frisian", "FY"},
	{74, "Kabardian", "KBD"},
	{75, "Northern Sotho", "NSO"},
	{76, "Sundanese", "SU"},
	{77, "Tibetan", "BO"},
	{78, "Central Atlas Tamazight", "TAM"},
	{79, "Avar", "AV"},
	{80, "Kurmanji", "KU"},
	{81, "Komi", "KV"},
	{82, "Santali", "SAT"},
	{83, "Sranan Tongo", "SRN"},
	{84, "Interlingua", "IA"},
	{85, "Low German", "ND"},
	{86, "Hawaiian", "HAW"},
	{87, "Kashmiri", "KS"},
	{88, "Latvian", "LV"},
	{89, "Yiddish", "YI"},
	{90, "Kikuyu", "KIK"},
	{91, "Scottish Gaelic", "GD"},
	{92, "Silesian", "SZL"},
	{93, "Venetian", "VEC"},
	{94, "Ossetian", "OS"},
	{95, "Norwegian Nynorsk", "NN"},
	{96, "Wolof", "WO"},
	{97, "Turkmen", "TK"},
	{98, "Lombard", "LO"},
	{99, "Crimean Tatar", "CRH"},
	{100, "Navajo", "NV"},
	{101, "Akan", "AK"},
	{102, "Cebuano", "CEB"},
	{103, "Waray", "WAR"},
	{104, "Norfolk", "PIH"},
	{105, "Bambara", "BM"},
	{106, "Oriya", "OR"},
	{107, "Georgian", "KA"},
	{108, "Kirghiz", "KY"},
	{109, "Maltese", "MT"},
	{110, "Papiamento", "PAP"},
	{111, "Sesotho", "ST"},
	{112, "Tongan", "TO"},
	{113, "Kanuri", "KR"},
	{114, "Komi-Permyak", "KOM"},
	{115, "Aragonese", "AN"},
	{116, "Rusyn", "RUE"},
	{117, "Ganda", "LG"},
	{118, "Chavacano", "CHV"},
	{119, "Bislama", "BI"},
	{120, "Tuvinian", "TYV"},
	{121, "Jamaican Patois", "JAM"},
	{122, "Kirmanjki", "kiu"},
	{123, "Sardinian", "SC"},
	{124, "Tahitian", "TY"},
	{125, "Chechen", "CE"},
	{126, "Venda", "VE"},
	{127, "Nauruan", "NA"},
	{128, "Buryat", "BUA"},
	{129, "Swazi", "SS"},
	{130, "Sami", "SE"},
	{131, "Udmurt", "UDM"},
	{132, "Bashkir", "BA"},
	{133, "Chamorro", "CH"},
	{134, "Lingala", "LN"},
	{135, "Zaza", "ZZA"},
	{136, "Sakha", "SAH"},
	{137, "Dhivehi", "DV"},
	{138, "Cherokee", "CHEROKEE"},
	{139, "Sorani", "CKB"},
	{140, "Kashubian", "CSB"},
	{141, "Tswana", "TN"},
}

